---
title: "Liam Wall"
date: 2024-03-10
bibliography: references.bib
---

## Introduction

Hello, my name is Liam Wall, and as of March 2024 I am a third year student in the Mathematics Department at the University of Toronto. I plan to graduate in 2025 with a applied mathematics in probability and statistics. I grew up in a suburb outside of Philadelphia, Pennsylvania, in the towns of Harleysville and Lansdale. I went to Catholic elementary and high school, played basketball, baseball, and lacrosse, and was active in my schools orchestra, band, and robotics club. In the University of Toronto I am active in the Artificial General Intelligence (AGI) Club, intramural sports, and a member of Sigma Chi, an international fraternity. After college I plan to gain experience in the data analytics industry and I do plan to improve and work in many other areas. I am capable of learning and offering valuable insight in my other areas of interest. 

A particular interest of mine is music, having played several instruments including classical training in viola and drums and a personal venture in guitar. I've played viola since my 2nd grade of school and have had the opportunity to play in the Kimmel Center for the Performing Arts in Philadelphia with the Archdiocesan Orchestra. As for the drums, I was taught by the late Tommy Scapino, a brilliant drummer from FILL IN, New York. Brilliant as confirmed by KISS when he became their replacement drummer for night and his many band-mates and students. Drums became my main instrument in high school for the band and I still will play drums with friends and previous band-mates. However, recently my passion has evolved into guitar over the past five years. 

If you want to ask me questions, give me money or offer me employment you can find my information the contact page.

## Acknowledgements

This website was produced using @rPRogram, @githubPages, and code made avaible by @heissCV at <https://github.com/andrewheiss/ath-quarto/blob/main/cv/index.qmd>.. 

